### PR TITLE
renamed sizeX sizeY and sizeZ -> size_x, size_y, size_z in all files

### PR DESCRIPTION
**Pull request by sroet**
This is the result fo running `%s/sizeX/size_x/g` on all files that popped up with:
`grep -R size[XYZ] --exclude-dir=build --exclude-dir=.ruff_cache  --exclude-dir=__pycache__ --exclude-dir=.git --exclude-dir=.mypy_cache --exclude=*.so -l`

the same with `sizeY` and `sizeZ`

### CODE REVIEW

**Comment by McHaillet** [comment]
I am getting on error with the unittests (all tests pass though, but its in the terminal output): 

```Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/marten/miniconda3/envs/pytom_env/lib/python3.11/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/home/marten/miniconda3/envs/pytom_env/lib/python3.11/unittest/main.py", line 101, in __init__
    self.parseArgs(argv)
  File "/home/marten/miniconda3/envs/pytom_env/lib/python3.11/unittest/main.py", line 150, in parseArgs
    self.createTests()
  File "/home/marten/miniconda3/envs/pytom_env/lib/python3.11/unittest/main.py", line 161, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marten/miniconda3/envs/pytom_env/lib/python3.11/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marten/miniconda3/envs/pytom_env/lib/python3.11/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marten/miniconda3/envs/pytom_env/lib/python3.11/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marten/coding/PyTomPrivate/tests/template_match_test.py", line 23, in <module>
    from pytom.agnostic.io import read
  File "/home/marten/miniconda3/envs/pytom_env/lib/python3.11/site-packages/pytom/agnostic/io.py", line 12, in <module>
    def read(filename, ndarray=True, order='F', keepnumpy=False, deviceID=None, dtype=None, read_optics_group=False) -> Union[xp.ndarray[float], pytom_lib.pytom_volume.vol]:
                                                                                                                              ~~~~~~~~~~^^^^^^^
TypeError: Argument 'item' has incorrect type (expected tuple, got type)```

**Comment by McHaillet** [comment]
`python -m unittest discover` in the E2Etests folder, has these results:

```
Ran 92 tests in 1067.289s

FAILED (failures=6, errors=5, skipped=6)
```

Will try to put some more detailed info of what failed !

**Comment by sroet** [comment]
> I am getting on error with the unittests (all tests pass though, but its in the terminal output):
> 
> ```
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "/home/marten/miniconda3/envs/pytom_env/lib/python3.11/unittest/__main__.py", line 18, in <module>
>     main(module=None)
>   File "/home/marten/miniconda3/envs/pytom_env/lib/python3.11/unittest/main.py", line 101, in __init__
>     self.parseArgs(argv)
>   File "/home/marten/miniconda3/envs/pytom_env/lib/python3.11/unittest/main.py", line 150, in parseArgs
>     self.createTests()
>   File "/home/marten/miniconda3/envs/pytom_env/lib/python3.11/unittest/main.py", line 161, in createTests
>     self.test = self.testLoader.loadTestsFromNames(self.testNames,
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/marten/miniconda3/envs/pytom_env/lib/python3.11/unittest/loader.py", line 220, in loadTestsFromNames
>     suites = [self.loadTestsFromName(name, module) for name in names]
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/marten/miniconda3/envs/pytom_env/lib/python3.11/unittest/loader.py", line 220, in <listcomp>
>     suites = [self.loadTestsFromName(name, module) for name in names]
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/marten/miniconda3/envs/pytom_env/lib/python3.11/unittest/loader.py", line 154, in loadTestsFromName
>     module = __import__(module_name)
>              ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/marten/coding/PyTomPrivate/tests/template_match_test.py", line 23, in <module>
>     from pytom.agnostic.io import read
>   File "/home/marten/miniconda3/envs/pytom_env/lib/python3.11/site-packages/pytom/agnostic/io.py", line 12, in <module>
>     def read(filename, ndarray=True, order='F', keepnumpy=False, deviceID=None, dtype=None, read_optics_group=False) -> Union[xp.ndarray[float], pytom_lib.pytom_volume.vol]:
>                                                                                                                               ~~~~~~~~~~^^^^^^^
> TypeError: Argument 'item' has incorrect type (expected tuple, got type)```
> ```

This also is an issue on master (template_match_test is not auto picked up by unittest discover)

**Comment by sroet** [comment]
all of these tests started failing on master as well, as cupy 12 seems to have disabled implicit casting from cupy to numpy. I am working on a seperate PR for that

**Comment by sroet** [comment]
@McHaillet PLease have another look, I did successfully complete all the E2E and unittests with a GPU

**Review by McHaillet — APPROVED** [review]
LGTM!

**Pull request merged**
