### PR TITLE
Fix e2e tests part 3

### PR DESCRIPTION
**Pull request by sroet**
this is a continuation of #128 and #123.

### CODE REVIEW

**Comment by sroet** [comment]
@McHaillet What is the deal with the GUIWidgets not being part of a testing class? Is it not supposed to work?

**Comment by sroet** [comment]
@McHaillet the `test_MicrographModellerTest` fails with:
```
AssertionError: 0.420651414087096 not greater than 0.75 : correlation is not sufficient between simulations
```
It seems like something is wrong and I am not just unlucky, other values I get are:
```
0.4629460782217853
0.3175072873139616
0.3920911222168034
0.537591323887431
0.3467634326484411
```

**Comment by McHaillet** [comment]
> I am also running into issues on `test_pytom_FullPipeline.pytom_MyFunctionTest.test_09_GenerateSubsetParticles` where the particles are assigned a score and a cutoff is determined.
> 
> The sum of scores is correct, but the cutoff is `1084` instead of the expected `>1160`. This expectation seems arbitrary (considering that there are 1500 particles), @McHaillet do you have any clue why this was set at this value?

The non-mirrored vs. mirrored matching should ideally be able to estimate the number of true positives in the tomogram. I guess that number was estimated to be more than 1160. I don't know what changed that makes the result different than before.

Perhaps we could visually inspect the tomogram and the locations to see whether the result is reliable?

**Comment by sroet** [comment]
@McHaillet I don't get a high enough resolution for test 19, I end up with a final resolution of 15.35 while a resolution of <10 is expected. I will rerun it on a different machine next week, but do you know if this is expected?

**Comment by McHaillet** [comment]
> @McHaillet I don't get a high enough resolution for test 19, I end up with a final resolution of 15.35 while a resolution of <10 is expected. I will rerun it on a different machine next week, but do you know if this is expected?

Well, I see the tests only runs the pipeline on a single tilt-series:

[`self.orignal_data = 'ftp://ftp.ebi.ac.uk/empiar/world_availability/10064/data/mixedCTEM_tomo3.mrc'`](https://github.com/sroet/PyTomPrivate/blob/aaf7fea521c6330a777f4fce3b51218b786a4c64/tests/E2ETests/test_pytom_FullPipeline.py#LL24C9-L24C107)

From what you said previously there were ~1100 ribosomes selected from this dataset. Going to 9A resolution I would find **very** surprising. If it was for all the 4 tilt-series in EMPIAR10064, it would be more reasonable (but still high).

So the 15.35 you get out seems more reasonable.

BTW, about the speed. I see in the paper of this dataset (https://www.sciencedirect.com/science/article/pii/S1047847716301034?via%3Dihub#s0010) that subtomograms were first extracted 2x binned (step 10 and 16 of full pipeline), with 80 px boxes instead of 100. For the unbinned step the boxes were 160 instead of 200. So we could easily get some speed up from reducing the box size. I also know from the tutorial (same dataset) that the box size is quite large, ribosomes still easily fit in with some overhang for the 160 px box.

**Comment by sroet** [comment]
I am currently running the full pipeline on my desktop but that will take a couple days, do you mind also running the full pipeline test on a GPU machine during review?

**Comment by McHaillet** [comment]
> I am currently running the full pipeline on my desktop but that will take a couple days, do you mind also running the full pipeline test on a GPU machine during review?

Will do

**Comment by McHaillet** [comment]
I will try to run the GPU tests overnight. Lets see what happens :)

**Comment by McHaillet** [comment]
It crashed at the image alignment because I installed in dev mode, that means this file does not exist: `/home/mchaillet/miniconda3/envs/pytom_env/lib/python3.8/site-packages/pytom/reconstruction/generateAlignedTiltImages.py`

I guess this file should anyway be in the bin folder, so I will move it there

**Comment by McHaillet** [comment]
Lol, it is already there... There are two copies of it apparently

**Comment by sroet** [comment]
alright, the test completed in 349059 s on my local desktop. @McHaillet please have a look :)

> I deleted the one in reconstruction, so it's only a bin script now.

Should we make that a separate issue/PR?

**Review by McHaillet — APPROVED** [review]
LGTM

**Pull request merged**
