### PR TITLE
include kernels for pytom/voltools correctly in setup

### PR DESCRIPTION
**Pull request by McHaillet**
Voltools could not transform with custom cuda kernels because they were not included during installation. I added an include statement to the MANIFEST to fix it.

### CODE REVIEW

**Review by sroet — APPROVED** [review]
LGTM, Is there an easy unittest to add for this? (preferably some import that we can attempt).

Feel free to merge if that is not the case.

**Comment by McHaillet** [comment]
Well, I found the bug beacuse I ran the unittests! In the Interpolation test it runs voltools on cpu and on gpu and checks whether forward-backward transform is accurate enough. But, I set it to skip the gpu test if its run in a Docker container (no gpu's for the github tests) or if cupy cannot be imported. I guess, where you ran the tests you did not have a gpu, so cupy could not be loaded?
I can change remove the skip but I assume it will then fail anyway

**Comment by sroet** [comment]
> I guess, where you ran the tests you did not have a gpu, so cupy could not be loaded?

That is correct

> I can change remove the skip but I assume it will then fail anyway

Yeah, that is not the correct solution for this. I think it some future we might need to register our own runners that have a GPU (so all the tests run there), but this is good enough for now :+1:

**Comment by McHaillet** [comment]
> Yeah, that is not the correct solution for this. I think it some future we might need to register our own runners that have a GPU (so all the tests run there), but this is good enough for now +1

Yea, that would be great

**Pull request merged**
