### PR TITLE
Fix coding style pytom/agnostic/correlation.py

### PR DESCRIPTION
**Pull request by sroet**
This will be one of many PRs that should do some fixing of the style/maintenance.

I will probably do one for every file, this one is for `pytom/agnostic/correlation.py`

After this PR the file should be formatted with `black` and have no `pylint` issues anymore.

It will also add/solve some files to the list in #147

### CODE REVIEW

**Comment by McHaillet** [comment]
Good idea, much needed!

I saw this linter coming by lately (https://github.com/charliermarsh/ruff) maybe nice to use?

**Comment by sroet** [comment]
> I saw this linter coming by lately (https://github.com/charliermarsh/ruff) maybe nice to use?

Looks very promising, will give that one a go (we might need to enable more than de default rules, but let's start there)

**Comment by McHaillet** [comment]
I ran the tests with this branch, but I get the error that python needs to be >= 3.9

**Comment by McHaillet** [comment]
Found that issue #62 also discusses a related problem. I am referencing it here to keep track of the issue.

**Comment by sroet** [comment]
alright @McHaillet it is now actually complete, sorry for the big PR. Please have a look

The following things are now true for `pytom/agnostic/correlation.py`:
- `mypy --strict` only complains about "implicit reexport
- `ruff check --select E,F,PL,N,RUF,NPY ` only complains about `PLR2004` (too strict in my opinion), and `PLR0913`/`PLR0912` (require big refactors (outside of the scope of this PR))
- `black` has been run on the file
For the whole state of the repo:
- `pytom -m unittest discover` has no errors from the `test` directory and no more than `master` for the `E2E` tests (I am still running the full pipeline but assume it is fine for now)

**Review by McHaillet — APPROVED** [review]
LGTM, but please wait with merging until I try on gpu.

**Comment by McHaillet** [comment]
Same things as before:
- test_pytomvolume_vs_numpy.py has an issue
- missing file in test_BinScripts.py
- and subprocesses running warning in pipeline test

So from my part, feel free to merge!

**Comment by sroet** [comment]
also passes on cpu for me, merging

**Pull request merged**
