### PR TITLE
Alter input arguments to coords2PL.py and change it to a console_script with an entrypoint

### LINKED ISSUE #160: coords2PL.py should have an argument for tomogram name
This way the resulting particle list has a correct origin tomogram name in the PickPosition.

### PR DESCRIPTION
**Pull request by sroet**
closes #160 

This PR will:

- [x] change the way the script is registered to a `console_scripts` with an `entry_point`
- [x] remove the duplicated file from `/pytom/bin`
- [x] add and deal with the new argument
- [x] added tests for the new argument

This PR also contains #166 (a5a4b99)

### CODE REVIEW

**Review by McHaillet — APPROVED** [review]
LGTM!

So one know adds the entry point functions to setup and it takes care of making them visible as executables?

**Comment by sroet** [comment]
> So one know adds the entry point functions to setup and it takes care of making them visible as executables?

I assume you meant *now* ? but yeah you can now both access them as executables in setup (also does the symlinking correctly if you do a developer install) and via direct function import (as done in the tests)

**Comment by sroet** [comment]
more info [here](https://setuptools.pypa.io/en/latest/userguide/entry_point.html), one useful one might be `gui_scripts` on top of the currently used `console_scripts`, which will open up a gui but no terminal if I read that correctly

**Comment by McHaillet** [comment]
> > So one know adds the entry point functions to setup and it takes care of making them visible as executables?
> 
> I assume you meant _now_ ? but yeah you can now both access them as executables in setup (also does the symlinking correctly if you do a developer install) and via direct function import (as done in the tests)

Neat!

**Pull request merged**
